orig_Team_key = "OrigTeam"
player_Name_key = "playerName"
year_key = "year"
price_Status_key = "priceStatus" # this key will be remove
dest_Team_key = "DestTeam"
price_key = "price"
type_key = "type"
dest_country_key = "DestCountry"
orig_country_key = "OrigCountry"

start_year = 2007
number_of_seasons = 9

# array of tuples each tuple is : (int: year , string: json file path contains all transferd for this year)
all_years_files_path = []
[all_years_files_path.append((start_year+i, "Transfers_"+str(start_year+i)+"_"+str(start_year+i+1)+".json")) for i in range(number_of_seasons)]


data_dir_path = "crawlerData"


teams = {}

teams["KANSAS CITY"] = ("KANSAS CITY", "USA")
teams["KAPFENBERGER SV"] = ("KAPFENBERGER SV", "Austria")
teams["KARLSRUHER"] = ("KARLSRUHER", "Germany")
teams["KARLSRUHE"] = ("KARLSRUHER", "Germany")
teams["KARPATY LVIV"] = ("KARPATY LVIV" "Ukraine")
teams["KASHIMA ANTLERS"] = ("KASHIMA ANTLERS", "Japan")
teams["KASHIWA REYSOL"] = ("KASHIWA REYSOL", "Japan")
teams["KASIMPASA"] = ("KASIMPASA", "Turkey")
teams["KAWASAKI FRONTALE"] = ("KAWASAKI FRONTALE", "Japan")
teams["KAYSERISPOR"] = ("KAYSERISPOR", "Turkey")
teams["KILMARNOCK"] = ("KILMARNOCK", "Scotland")
teams["KLN"] = ("KOLN", "Germany")
teams["KOLN"] = ("KOLN", "Germany")
teams["KOBENHAVN"] = ("KOBENHAVN", "Denemark")
teams["KOPER"] = ("KOPER", "Slovenia")
teams["KORTRIJK"] = ("KORTRIJK", "Belgium")
teams["KRYLYA S SAMARA"] = ("KRYLYA S SAMARA", "Russia")
teams["KUBAN"] = ("KUBAN", "Russia")
teams["KUBAN KRASNODAR"] = ("KUBAN", "Russia")

teams["LA EQUIDAD"] = ("LA EQUIDAD", "Colombia")
teams["LA GALAXY"] = ("LA GALAXY", "USA")
teams["LANUS"] = ("LANUS", "Argentina")
teams["LAS PALMAS"] = ("LAS PALMAS", "Spain")
teams["LATINA"] = ("LATINA", "Italy")
teams["LAVAL"] = ("LAVAL", "Canada")
teams["LAZIO"] = ("LAZIO", "Italy")
teams["LDU QUITO"] = ("LDU QUITO", "Ecuador")
teams["LE HAVRE"] = ("LE HAVRE", "France")

teams["LE MANS"] = ("LE MANS", "France")
teams["LECCE"] = ("LECCE", "Italy")
teams["LECH POZNAN"] = ("LECH POZNAN", "Poland")
teams["LECHIA GDANSK"] = ("LECHIA GDANSK", "Poland")
teams["LEEDS"] = ("LEEDS", "England")
teams["LEEDS UNITED"] = ("LEEDS", "England")
teams["LEGIA WARSAW"] = ("LEGIA WARSAW", "Poland")
teams["LEGIA WARSZAWA"] = ("LEGIA WARSAW", "Poland")
teams["LEICESTER"] = ("LEICESTER", "England")
teams["LEIXES SC"] = ("LEIXES SC", "Portogal")

teams["LENS"] = ("LENS", "France")
teams["LEVANTE"] = ("LEVANTE", "Spain")
teams["LEVERKUSEN"] = ("LEVERKUSEN", "Germany")
teams["LEVSKI SOFIA"] = ("LEVSKI SOFIA", "Bulgria")
teams["LIBERTY PROFESSIONALS"] = ("LIBERTY PROFESSIONALS", "Ghana")
teams["LIERSE"] = ("LIERSE", "Belgium")
teams["LILLE"] = ("LILLE", "France")
teams["LILLESTROM"] = ("LILLESTROM", "Norway")
teams["LITEX"] = ("LITEX", "Bulgria")
teams["LIV MONTEVIDEO"] = ("LIVERPOOL MONTEVIDEO", "Uruguay")

teams["LIVERPOOL"] = ("LIVERPOOL", "England")
teams["LIVERPOOL DE MONTEVIDEO"] = ("LIVERPOOL MONTEVIDEO", "Uruguay")
teams["LIVORNO"] = ("LIVORNO", "Italy")
teams["LLANEROS"] = ("LLANEROS", "Colombia")
teams["LOKOMOTIV MOSCOW"] = ("LOKOMOTIV MOSCOW", "Russia")
teams["LOKOMOTIV"] = ("LOKOMOTIV MOSCOW", "Russia")
teams["LOK MOSCOW"] = ("LOKOMOTIV MOSCOW", "Russia")

teams["LORIENT"] = ("LORIENT", "France")
teams["LUDOGORETS"] = ("LUDOGORETS", "Bulgria")
teams["LUZERN"] = ("LUZERN", "Switzerland")
teams["LYNGBY"] = ("LYNGBY", "Denemark")
teams["LYON"] = ("LYON", "France")
teams["MACCABI HAIFA"] = ("MACCABI HAIFA", "Israel")
teams["MACCABI TEL AVIV"] = ("MACCABI TEL AVIV", "Israel")

teams["MAINZ"] = ("MAINZ", "Germany")
teams["MALAGA"] = ("MALAGA", "Spain")
teams["MALLORCA"] = ("MALLORCA", "Spain")
teams["MALMO"] = ("MALMO", "Sweden")
teams["MALMO FF"] = ("MALMO", "Sweden")
teams["MALMOE FF"] = ("MALMO", "Sweden")


teams["MANCESTER CITY"] = ("MANCHESTER CITY", "England")
teams["MANCHESTER C"] = ("MANCHESTER CITY", "England")
teams["MANCHESTER CITY"] = ("MANCHESTER CITY", "England")
teams["MANCHESTERY CITY"] = ("MANCHESTER CITY", "England")
teams["MANCHESTER UNITED"] = ("MANCHESTER UNITED", "England")
teams["MANCHESTER UTD"] = ("MANCHESTER UNITED", "England")

teams["MANFREDONIA"] = ("MANFREDONIA", "Italy")
teams["MARIBOR"] = ("MARIBOR", "Slovenia")
teams["MARITIMO"] = ("MARITIMO", "Portugal")
teams["MARSEILLE"] = ("MARSEILLE", "France")
teams["MELBOURNE HEART"] = ("MELBOURNE", "Australia")
teams["MELBOURNE VICTORY"] = ("MELBOURNE", "Australia")

teams["MELFI"] = ("MELFI", "Italy")
teams["MELGAR AREQUIPA"] = ("MELGAR AREQUIPA", "Peru")
teams["MESSINA"] = ("MESSINA", "Italy")

teams["METALIST"] = ("METALIST", "Ukraine")
teams["METALIST KHARKIV"] = ("METALIST", "Ukraine")
teams["METALLURG DONETSK"] = ("METALLURG DONETSK", "Ukraine")
teams["METZ"] = ("METZ", "France")

teams["MFK KOSICE"] = ("MFK KOSICE", "Slovakia")
teams["MIDDLESBROUGH"] = ("MIDDLESBROUGH", "England")
teams["MIDTJYLLAND"] = ("MIDTJYLLAND", "Denemark")
teams["MILAN"] = ("FC MILAN", "Italy")
teams["MJALLBY"] = ("MJALLBY", "Sweden")
teams["MK DONS"] = ("MK DONS", "England")
teams["MODENA"] = ("MODENA", "Italy")
teams["MOGREN"] = ("MOGREN", "Montenegro")
teams["MOLDE"] = ("MOLDE", "Norway")
teams["MOLDE FK"] = ("MOLDE", "Norway")

teams["MONACO"] = ("MONACO", "France")
teams["MONTERREY"] = ("MONTERREY", "Mexico")
teams["MONTPELLIER"] = ("MONTPELLIER", "Mexico")
teams["MOREIRENSE"] = ("MOREIRENSE", "Portugal")

teams["MORELIA"] = ("MORELIA", "Mexico")
teams["MOTAGUA"] = ("MOTAGUA", "Honduras")
teams["MOTAGUA"] = ("MOREIRENSE", "Portugal")
teams["MOTHERWELL"] = ("MOTHERWELL", "Scotland")
teams["MSI RIGHTS"] = ("MSI RIGHTS", "Russia")
teams["MSK ZILINA"] = ("MSK ZILINA", "Slovakia")
teams["MTK BUDAPEST"] = ("MTK BUDAPEST", "Hungary")
teams["MUNICH 1860"] = ("MUNICH 1860", "Germany")
teams["MVV MAASTRICHT"] = ("MVV MAASTRICHT", "Holland")
teams["N CHICAGO"] = ("CHICAGO", "USA")

teams["NAC BREDA"] = ("NAC BREDA", "Holland")
teams["N NACIONAL"] = ("NACIONAL MONTEVIDEO", "Uruguay")
teams["NACIONAL MADEIRA"] = ("NACIONAL MADEIRA", "Portugal")
teams["NACIONAL MONTEVIDEO"] = ("NACIONAL MONTEVIDEO", "Uruguay")
teams["NAFTA"] = ("NAFTA", "Slovenia")
teams["NAGOYA"] = ("NAGOYA", "Japan")
teams["NANTES"] = ("NANTES", "France")
teams["NANCY"] = ("NANTES", "France")
teams["NAPOLI"] = ("NAPOLI", "Italy")

teams["NAUTICO"] = ("NAUTICO", "Brazil")
teams["NEC NIJMEGEN"] = ("NIJMEGEN", "Holland")
teams["NESET FK"] = ("NESET FK", "Norway")
teams["NEUCHATEL XAMAX"] = ("NEUCHATEL XAMAX", "Switzerland")
teams["NEW YORK RED BULLS"] = ("NEW YORK RED BULLS", "USA")
teams["NEWCASTLE"] = ("NEWCASTLE", "England")
teams["NEWCASTLE FC"] = ("NEWCASTLE", "England")
teams["NEWCASTLE JETS"] = ("NEWCASTLE", "England")

teams["NEWELLS"] = ("NEWELLS", "Argentina")
teams["NEWELLS OLD BOYS"] = ("NEWELLS", "Argentina")
teams["NEWPORT COUNTY"] = ("NEWPORT COUNTY", "England")
teams["NICE"] = ("NICE", "France")
teams["NIORT"] = ("NIORT", "France")

teams["NK DOMZALE"] = ("NK DOMZALE", "Slovania")
teams["NK MARIBOR"] = ("NK MARIBOR", "Slovenia")
teams["NK ZAGREB"] = ("NK ZAGREB", "Croatia")
teams["NORDSJAELLAND"] = ("NORDSJAELLAND", "Denemark")
teams["NORTHAMPTON"] = ("NORTHAMPTON", "England")
teams["NORWICH"] = ("NORWICH", "England")
teams["NORWICH CITY"] = ("NORWICH", "England")


teams["NOTTINGHAM FOREST"] = ("NOTTINGHAM FOREST", "England")
teams["NOTT FOREST"] = ("NOTTINGHAM FOREST", "England")
teams["NOTTS COUNTY"] = ("NOTTS COUNTY", "England")
teams["NOVARA"] = ("NOVARA", "Italy")
teams["NUMANCIA"] = ("NUMANCIA", "Spain")
teams["NURNBERG"] = ("NURNBERG", "Germany")
teams["NUREMBERG"] = ("NURNBERG", "Germany")

teams["NY RED BULLS"] = ("NY RED BULLS", "USA")
teams["NY RED BULLS"] = ("NY RED BULLS", "USA")
teams["O HIGGINS"] = ("O HIGGINS", "Chile")
teams["ODENSE"] = ("ODENSE", "Denemark")
teams["OFI CRETE"] = ("OFI CRETE", "Greece")
teams["OFI FC"] = ("OFI CRETE", "Greece")
teams["OFK BELGRADE"] = ("OFK BELGRAD", "Serbia")
teams["OFK BEOGRAD"] = ("OFK BELGRAD", "Serbia")
teams["OFK BEOGRAD"] = ("NURNBERG", "Germany")
teams["OH LEUVEN"] = ("OH LEUVEN", "Belgium")
teams["OLDHAM"] = ("OLDHAM", "England")
teams["OLHANENSE"] = ("OLHANENSE", "Portugal")

teams["OLYMP MARSEILLE"] = ("MARSEILLE", "France")
teams["OLYMPIQUE MARSEILLE"] = ("MARSEILLE", "France")
teams["OLYMPIACOS"] = ("OLYMPIAKOS", "Greece")
teams["OLYMPIAKOS"] = ("OLYMPIAKOS", "Greece")
teams["ONCE CALDAS"] = ("ONCE CALDAS", "Colombia")
teams["ORDUSPOR"] = ("ORDUSPOR", "Turkey")
teams["OREBRO"] = ("OREBRO", "Sweden")
teams["OSASUNA"] = ("OSASUNA", "Spain")
teams["OSTERSUNDS"] = ("OSTERSUNDS", "Sweden")
teams["P EJIDO"] = ("EJIDO", "Spain")
teams["PACHUCA"] = ("PACHUCA", "Mexico")
teams["PACOS FERREIRA"] = ("PACOS FERREIRA", "Portugal")
teams["PACOS FERREITA"] = ("PACOS FERREIRA", "Portugal")
teams["PADERBORN"] = ("PADERBORN", "Germany")
teams["PADROENSE"] = ("PADROENSE", "Portugal")
teams["PALERMO"] = ("PALERMO", "Italy")
teams["PALERMA"] = ("PALERMO", "Italy")
teams["PALMEIRAS"] = ("PALMEIRAS", "Brazil")
teams["PANATHINAIKOS"] = ("PANATHINAIKOS", "Greece")
teams["PANDURII"] = ("PANDURII", "Romania")
teams["PAOK"] = ("PAOK SALONIKA", "Greece")
teams["PAOK SALONIKA"] = ("PAOK SALONIKA", "Greece")
teams["PARAGUAY"] = ("PARAGUAY FC", "Paraguay")
teams["PARIS SG"] = ("PARIS SG", "France")
teams["PARIS SAINTGERMAIN"] = ("PARIS SG", "France")
teams["PARIS SAINT GERMAIN"] = ("PARIS SG", "France")
teams["PARMA"] = ("PARMA", "Italy")

teams["PARTIZAN BELGRADE"] = ("PARTIZAN BELGRADE", "Serbia")
teams["PARTIZAN"] = ("PARTIZAN BELGRADE", "Serbia")
teams["PAS GIANNINA"] = ("PAS GIANNINA", "Greece")
teams["PENAROL"] = ("PENAROL", "Uruguay")
teams["PESCARA"] = ("PESCARA", "Italy")
teams["PESCARA CALCIO"] = ("PESCARA", "Italy")
teams["PETERBOROUGH"] = ("PETERBOROUGH", "England")
teams["PIACENZA"] = ("PIACENZA", "Italy")
teams["PISA CALCIO"] = ("PISA CALCIO", "Italy")
teams["POLI TIMISOARA"] = ("POLI TIMISOARA", "Romonia")
teams["POLONIA"] = ("POLONIA", "Poland")
teams["PONFERRADINA"] = ("PONFERRADINA", "Spain")
teams["PONTE PRETA"] = ("PONTE PRETA", "Brazil")
teams["PORTO"] = ("PORTO", "Portugal")
teams["PORTSMOUTH"] = ("PORTSMOUTH", "England")
teams["POTENZA"] = ("POTENZA", "Italy")
teams["PRESOV"] = ("PRESOV", "Slovakia")
teams["PRESTON"] = ("PRESTON", "England")
teams["PROGRESO"] = ("PROGRESO", "Mexico")
teams["PSG"] = ("PARIS SG", "France")
teams["PSV"] = ("PSV EINDHOVEN", "Holland")
teams["PSV EINDHOVEN"] = ("PSV EINDHOVEN", "Holland")
teams["PUERTOLLANO"] = ("PUERTOLLANO", "Spain")
teams["QPR"] = ("QPR", "England")
teams["QRP"] = ("QPR", "England")
teams["QUINDIO"] = ("QUINDIO", "Colombia")
teams["R C AVELLANEDA"] = ("R C AVELLANEDA", "Argentina")
teams["R SALT LAKE"] = ("R SOLT LAKE", "USA")
teams["RACING SANTANDER"] = ("RACING SANTANDER", "Spain")
teams["RACING CLUB"] = ("RACING SANTANDER", "Spain")
teams["R SANTANDER"] = ("RACING SANTANDER", "Spain")
teams["R SOCIEDAD"] = ("REAL SOCIEDAD", "Spain")
teams["RAD"] = ("RAD", "Serbia")
teams["RAKOSPALOTAI"] = ("RAKOSPALOTAI", "Hungary")
teams["RANGERS"] = ("RANGERS", "Scotland")
teams["RAPID VIENNA"] = ("RAPID VIENNA", "Austria")
teams["RAPID WIEN"] = ("RAPID VIENNA", "Austria")
teams["RAYO VALLECANO"] = ("RAYO VALLECANO", "Spain")
teams["READING"] = ("READING", "England")
teams["REAL BETIS"] = ("REAL BETIS", "Spain")